theme = "plain"

[icons]
name = "awesome5"

[icons.overrides]
backlight_empty = ""
backlight_full = ""
backlight_1 = ""
backlight_2 = ""
backlight_3 = ""
backlight_4 = ""
backlight_5 = ""
backlight_6 = ""
backlight_7 = ""
backlight_8 = ""
backlight_9 = ""
backlight_10 = ""
backlight_11 = ""
backlight_12 = ""
backlight_13 = ""

[[block]]
block = "net"
device = "wlp2s0"
format = "{ssid} {signal_strength} {graph_down}"
interval = 5

[[block]]
block = "sound"

[[block]]
block = "backlight"

[[block]]
block = "cpu"

[[block]]
block = "memory"
format_mem = "{mem_total_used_percents}"

[[block]]
block = "temperature"
format = "{average}"
chip = "*-isa-*"

[[block]]
block = "battery"

[[block]]
block = "time"
format = "%Z %d %a %H:%M"
timezone = "America/Los_Angeles"

[[block]]
block = "time"
format = "%Z %d %a %H:%M"
timezone = "America/New_York"

[[block]]
block = "time"
format = "%Z %d %a %H:%M"
timezone = "Asia/Shanghai"
